In [30]:
 !pip install pymupdf
 !pip install pdfplumber
 !pip install faiss-cpu

Requirement already satisfied: pymupdf in /usr/local/lib/python3.12/dist-packages (1.27.2.2)
Requirement already satisfied: pdfplumber in /usr/local/lib/python3.12/dist-packages (0.11.9)
Requirement already satisfied: pdfminer.six==20251230 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (20251230)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Requirement already satisfied: pypdfium2>=4.18.0 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (5.7.0)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.6)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)
Requirement already satisfied: faiss-cpu in /usr/local/lib/python3.12/dist-packages (1.13.2)
Requirement already satisfied: numpy<3.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.0)

In [1]:
from util import StructuredDataLoader, UnstructuredDataLoader

warning: The `fitz` API is deprecated and will be removed in future. Use `import pymupdf` instead.

In [3]:
st_loader = StructuredDataLoader()

file_path = "amazon_reviews.csv"
data = st_loader.load_csv(file_path)

data.head()

,product_name,product_id,price,description,reviewer_name,rating,review_title,review_body,review_date
0,Stock process,G7GD90FUAD,64.99,Think type good coach part. Medical herself me...,Richard Reilly,5,Sort spring medical already,Movie reality service throughout everybody sor...,2022-01-24
1,Area skin president hair upon,SYSFMJBX59,281.87,Trouble answer for major find. Only country ed...,Sean Chase,1,Take drive money hope door reduce behind,Before issue reflect will. Little pay change o...,2021-04-25
2,Well on grow business good indeed measure,EMBQF60QVR,475.05,You off cold rest course little concern. Witho...,Michael Ritter,4,Heavy beautiful still party rock boy easy succ...,Similar page recently commercial system employ...,2021-01-25
3,As item bit old dark,42830GWDNS,64.96,Material condition out shake. Everybody hotel ...,Cynthia Stewart,5,Suddenly democratic really high thousand seem ...,Really possible carry hold pick stay goal. Det...,2024-10-30
4,Myself agreement reveal owner why myself,3BFRSTIFDF,474.06,Town with seem follow most option sea. Own coa...,Michael Underwood,3,Nation just fear human international,Describe fact film entire card him. Too item s...,2020-11-25

In [4]:
unstr_loader = UnstructuredDataLoader()

In [5]:
text = unstr_loader.extract_text_from_pdf("Table_Reconstruction.pdf")

In [35]:
# text

In [6]:
tables_md, tables_df = unstr_loader.extract_tables_from_pdf("Table_Reconstruction.pdf")

In [7]:
tables_md[2]

'--- Table 1 on Page 8 ---\n| **Method** | **IoU** | **FinTabNet** | **ICDAR-13** | **Sci-TSR** | **TUCD** |\n| --- | --- | --- | --- | --- | --- |\n|  |  | TSR-F1↑ | TSR-F1↑ | TSR-F1↑ | TSR-F1↑ |\n| TS-Net\nOurs†\nOurs‡ | 0.5 | 0.898\n0.906\n0.944 | 0.904\n0.903\n0.904 | 0.876\n0.880\n0.894 | 0.900\n0.889\n0.918 |\n| TS-Net\nOurs†\nOurs‡ | 0.6 | 0.848\n0.892\n0.920 | 0.886\n0.903\n0.904 | 0.864\n0.878\n0.894 | 0.871\n0.889\n0.918 |\n| TS-Net\nOurs†\nOurs‡ | 0.7 | 0.704\n0.802\n0.868 | 0.720\n0.820\n0.852 | 0.682\n0.746\n0.823 | 0.722\n0.797\n0.839 |\n| TS-Net\nOurs†\nOurs‡ | 0.8 | 0.496\n0.561\n0.680 | 0.597\n0.675\n0.748 | 0.565\n0.637\n0.714 | 0.582\n0.659\n0.735 |\n| TS-Net\nOurs†\nOurs‡ | 0.9 | 0.120\n0.325\n0.404 | 0.292\n0.307\n0.454 | 0.255\n0.296\n0.368 | 0.289\n0.301\n0.408 |'

In [55]:
tables_df[2]

,Method,IoU,FinTabNet,ICDAR-13,Sci-TSR,TUCD
0,None,None,TSR-F1↑,TSR-F1↑,TSR-F1↑,TSR-F1↑
1,TS-Net\nOurs†\nOurs‡,0.5,0.898\n0.906\n0.944,0.904\n0.903\n0.904,0.876\n0.880\n0.894,0.900\n0.889\n0.918
2,TS-Net\nOurs†\nOurs‡,0.6,0.848\n0.892\n0.920,0.886\n0.903\n0.904,0.864\n0.878\n0.894,0.871\n0.889\n0.918
3,TS-Net\nOurs†\nOurs‡,0.7,0.704\n0.802\n0.868,0.720\n0.820\n0.852,0.682\n0.746\n0.823,0.722\n0.797\n0.839
4,TS-Net\nOurs†\nOurs‡,0.8,0.496\n0.561\n0.680,0.597\n0.675\n0.748,0.565\n0.637\n0.714,0.582\n0.659\n0.735
5,TS-Net\nOurs†\nOurs‡,0.9,0.120\n0.325\n0.404,0.292\n0.307\n0.454,0.255\n0.296\n0.368,0.289\n0.301\n0.408

In [56]:
unstr_loader.max_chunk_size = 1000

In [57]:
chunks = unstr_loader.chunk_text(text[0], overlap = 100)

In [58]:
len(chunks)

52

In [59]:
len(chunks[0])

1000

## Embedding and Retreival

In [60]:
%pip install -q -U "google-genai>=1.0.0"

In [44]:
!pip install python_dotenv

Requirement already satisfied: python_dotenv in /usr/local/lib/python3.12/dist-packages (1.2.2)

In [61]:
from dotenv import load_dotenv

load_dotenv("config.env")

True

In [62]:
from google import genai
import os

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

In [63]:
MODEL_ID = "gemini-embedding-001"

In [64]:
result = client.models.embed_content(model = MODEL_ID, contents = chunks)

In [65]:
dim = len(result.embeddings[0].values)

In [66]:
dim

3072

In [67]:
import numpy as np
embeddings = np.empty((len(chunks), dim))

In [68]:
for i, embedding in enumerate(result.embeddings):
  embeddings[i] = np.array(embedding.values)

In [69]:
embeddings.shape

(52, 3072)

In [70]:
from util import FaissRetriever

In [71]:
retriever = FaissRetriever(embedding_dim=dim)

In [72]:
retriever.add(embeddings, chunks)

In [73]:
query = "TSR-Net"
query_embed = client.models.embed_content(model = MODEL_ID, contents = [query])
query_embedding = np.array(query_embed.embeddings[0].values).reshape(-1, dim)

In [74]:
retriever.retrieve(query_embedding)

['hat are far\napart in the two-dimensional space. To handle this prob-\nlem, we propose TSR-Net for structure recognition which\nuses the existing DGCNN architecture [22]. Our formulation\nuses rectilinear adjacencies instead of row/column adjacen-\ncies [22, 24]. Recursive parsing of rectilinear adjacencies\nhelps to build better long-range visual row/column associa-\ntions.\nOur contributions can be summarized as follows:\n• Introduce channel attention [19] for table object detec-\ntion and define two additional regularizers — conti-\nnuity and overlapping loss between every pair of cells\nin addition to the alignment loss from [24]. We use\ntrainable loss-weights for these losses and formulate a\nmin-max optimization problem for faster convergence.\n• Formulate structure recognition using rectilinear adja-\ncencies instead of row/column adjacencies, eliminat-\ning the need for complex post-processing heuristics for\ngenerating row and column spanning information for\nevery cell.\n• Introduce modestly si',
 'shown in\nthe supplementary material).\nTo detect table cells, we propose TOD-Net, where we\naugment the cell detection network of TabStruct-Net [24]\nwith additional loss components to further improve the table\nobject performance (rows/columns/cells) detection. These\nlosses (formulated as regularizers) improve cell detection\nperformance on high IoU thresholds by pairwise modelling\nof structural constraints. It allows for an improved bound-\ning box detection despite presence of non-informative vi-\nsual features in a specific table region using information\nfrom other cells detected in a different region of the table.\nOnce table cells are located precisely, extracting struc-\nture as an XML or any other predefined format is relatively\neasier.\nHowever, for extremely dense tables with many\nmulti-row and multi-column spanning cells, it may still be\nchallenging to build associations between cells that are far\napart in the two-dimensional space. To handle this prob-\nlem, we propose TSR-Net for str',
 '(refer sup-\nplementary paper)2. The resulting dataset follows all the\nconstraints that we model in the TOD-Net.\nFor evalu-\nation also, we pre-process ICDAR-2013 [8], cTDaR [7],\nSciTSR [4], PubTabNet [42] and FinTabNet [41] datasets\nbefore computing IoU with the corresponding predictions.\nSince UNLV [27] and TUCD datasets already have annota-\ntions for cells adhering to alignment constraints, we directly\nused them for evaluation. Further, during training and eval-\nuation, we use the non-maximal suppression threshold of\n0.8 during proposal generation to reduce the false nega-\ntives substantially. We train TSR-Net in two steps: In the\nfirst stage, we use pre-processed ground-truth cell boxes\nand corresponding start-row, start-column, end-row, and\nend-column indices to generate target rectilinear adjacency\nmatrices. In the second stage, we generate predictions of\nthe training set using TOD-Net to compute its overlap with\nthe ground-truth to find start-row, start-column, end-row,\n1TUCD data',
 '.903\n0.878\n0.889\nOurs‡\n0.920\n0.904\n0.894\n0.918\nTS-Net\n0.704\n0.720\n0.682\n0.722\nOurs†\n0.7 0.802\n0.820\n0.746\n0.797\nOurs‡\n0.868\n0.852\n0.823\n0.839\nTS-Net\n0.496\n0.597\n0.565\n0.582\nOurs†\n0.8 0.561\n0.675\n0.637\n0.659\nOurs‡\n0.680\n0.748\n0.714\n0.735\nTS-Net\n0.120\n0.292\n0.255\n0.289\nOurs†\n0.9 0.325\n0.307\n0.296\n0.301\nOurs‡\n0.404\n0.454\n0.368\n0.408\nTable 3. Shows the comparison between the performances of the\nproposed network and TabStruct-Net (TS-Net) [24] on cell detec-\ntion and table structure recognition of dataset over various IoU\nthresholds.TSR: indicates table structure recognition.\nWe use\nFinTabNet [41] dataset for training.\nexamples in the supplementary material. Since rectilinear\nadjacencies are predicted between every pair of cells, in-\nference time is in the order of square of number of cells\nlocated. For table images with 20 cells, inference time is\nabout 10 seconds which goes upto 50 seconds for images\nwith 200 cells.\nF1 based on Varying IoU Thresholds\nFor table cell\ndetection, the IoU thre',
 'r Test Set\nTraining\nICDAR-2013\nSciTSR\nSciTSR Comp\nICDAR-19\nTUCD\nMethod\nDataset\nEC\nP↑\nR↑\nF1↑P↑\nR↑\nF1↑P↑\nR↑\nF1↑P↑\nR↑\nF1↑P↑\nR↑\nF1↑\nDeepDeSRT [26]\nICDAR-13\n0.96 0.87 0.91 -\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\nSPLERGE(H) [30]\nPrivate\n0.96 0.95 0.95 -\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\nSPLIT [30]\nPrivate\nSEC 0.87 0.87 0.87 0.92 0.97 0.97 0.91 0.88 0.90 0.70 0.67 0.69 0.87 0.86 0.86\nTabStruct-Net [24] SciTSR\n0.92 0.90 0.91 0.93 0.91 0.92 0.91 0.88 0.90 0.60 0.57 0.58 0.90 0.89 0.90\nGTE-Cell [41]\nFinTabNet\n0.96 0.97 0.96 -\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\n-\nSEM [40]\nSciTSR\n-\n-\n-\n0.98 0.97 0.97 0.97 0.95 0.96 -\n-\n-\n-\n-\n-\nLGPMA [23]\nSciTSR\n0.93 0.98 0.95 0.98 0.99 0.99 0.97 0.99 0.98 -\n-\n-\n-\n-\n-\nDeepDeSRT [26]\nFinTabNet\n0.82 0.80 0.81 0.87 0.85 0.86 0.85 0.83 0.84 0.55 0.51 0.53 0.73 0.70 0.72\nDGCNN† [22, 24]\nFinTabNet\n0.94 0.93 0.94 0.91 0.89 0.90 0.89 0.88 0.89 0.73 0.70 0.71 0.89 0.87 0.88\nDGCNN‡ [22, 24]\nFinTabNet\n0.96 0.95 0.96 0.91 0.90 0.91 0.90 0.89 0.89 0.76 0.73 0.74 0.92 0.91 0.91\nTabStruct-Net [24] FinTabNet\nSEC 0.95 0.94 ']